/*
 *
 */
package com.lppbpl;
// TODO: Auto-generated Javadoc
// Generated by proto2javame, Tue May 22 15:05:13 IST 2012.

/**
 * The Class BgReadingType.
 */
public final class BgReadingType {

	/** The Constant NONE. */
	public static final int NONE = 0;

	/** The Constant FASTING. */
	public static final int FASTING = 1;

	/** The Constant POST. */
	public static final int POST = 2;

	/** The Constant RANDOM. */
	public static final int RANDOM = 3;

	/**
	 * Method getStringValue.
	 * @param value int
	 * @return String
	 */
	public static String getStringValue(int value) {
		String retValue;

		if (value == 0) {
			retValue = "NONE";

		} else if (value == 1) {
			retValue = "FASTING";

		} else if (value == 2) {
			retValue = "POST";

		} else if (value == 3) {
			retValue = "RANDOM";

		} else {
			retValue = "";

		}

		return retValue;
	}
}
