/*
 *
 */
package com.lppbpl;
// TODO: Auto-generated Javadoc
// Generated by proto2javame, Tue May 22 15:05:13 IST 2012.

/**
 * The Class DeviceStatus.
 */
public final class DeviceStatus {

	/** The Constant NoUserPaired. */
	public static final int NoUserPaired = 1;

	/** The Constant UserPaired. */
	public static final int UserPaired = 2;

	/**
	 * Method getStringValue.
	 * @param value int
	 * @return String
	 */
	public static String getStringValue(int value) {
		String retValue;

		if (value == 1) {
			retValue = "NoUserPaired";

		} else if (value == 2) {
			retValue = "UserPaired";

		} else {
			retValue = "";

		}

		return retValue;
	}
}
