/*
 *
 */
package com.lppbpl;
// TODO: Auto-generated Javadoc
// Generated by proto2javame, Tue May 22 15:05:13 IST 2012.

/**
 * The Class EcgLead.
 */
public final class EcgLead {

	/** The Constant LEAD1. */
	public static final int LEAD1 = 1;

	/** The Constant LEAD2. */
	public static final int LEAD2 = 2;

	/** The Constant LEAD3. */
	public static final int LEAD3 = 3;

	/** The Constant MCL1. */
	public static final int MCL1 = 4;

	/** The Constant MCL2. */
	public static final int MCL2 = 5;

	/** The Constant MCL3. */
	public static final int MCL3 = 6;

	/** The Constant MCL4. */
	public static final int MCL4 = 7;

	/** The Constant MCL5. */
	public static final int MCL5 = 8;

	/** The Constant MCL6. */
	public static final int MCL6 = 9;

	/** The Constant AVR. */
	public static final int AVR = 10;

	/** The Constant AVL. */
	public static final int AVL = 11;

	/** The Constant AVF. */
	public static final int AVF = 12;

	/**
	 * Method getStringValue.
	 * @param value int
	 * @return String
	 */
	public static String getStringValue(int value) {
		String retValue;

		if (value == 1) {
			retValue = "LEAD1";

		} else if (value == 2) {
			retValue = "LEAD2";

		} else if (value == 3) {
			retValue = "LEAD3";

		} else if (value == 4) {
			retValue = "MCL1";

		} else if (value == 5) {
			retValue = "MCL2";

		} else if (value == 6) {
			retValue = "MCL3";

		} else if (value == 7) {
			retValue = "MCL4";

		} else if (value == 8) {
			retValue = "MCL5";

		} else if (value == 9) {
			retValue = "MCL6";

		} else if (value == 10) {
			retValue = "AVR";

		} else if (value == 11) {
			retValue = "AVL";

		} else if (value == 12) {
			retValue = "AVF";

		} else {
			retValue = "";

		}

		return retValue;
	}
}
