/*
 *
 */
package com.lppbpl;
// Generated by proto2javame, Tue May 22 15:05:13 IST 2012.

import net.jarlehansen.protobuf.javame.AbstractOutputWriter;
import net.jarlehansen.protobuf.javame.ComputeSizeUtil;
import net.jarlehansen.protobuf.javame.UninitializedMessageException;
import net.jarlehansen.protobuf.javame.input.DelimitedInputStream;
import net.jarlehansen.protobuf.javame.input.DelimitedSizeUtil;
import net.jarlehansen.protobuf.javame.input.InputReader;
import net.jarlehansen.protobuf.javame.input.taghandler.DefaultUnknownTagHandlerImpl;
import net.jarlehansen.protobuf.javame.input.taghandler.UnknownTagHandler;
import net.jarlehansen.protobuf.javame.output.OutputWriter;

import java.io.IOException;
import java.io.InputStream;

// TODO: Auto-generated Javadoc
/**
 * The Class EcgMeasurementList.
 */
public final class EcgMeasurementList extends AbstractOutputWriter {

	/** The unknown tag handler. */
	private static UnknownTagHandler unknownTagHandler = DefaultUnknownTagHandlerImpl.newInstance();

	/** The ecg timestamp. */
	private final long ecgTimestamp;

	/** The Constant fieldNumberEcgTimestamp. */
	private static final int fieldNumberEcgTimestamp = 1;

	/** The measurement id. */
	private final int measurementId;

	/** The Constant fieldNumberMeasurementId. */
	private static final int fieldNumberMeasurementId = 2;

	/** The has measurement id. */
	private final boolean hasMeasurementId;


	/**
	 * Method newBuilder.
	 * @return Builder
	 */
	public static Builder newBuilder() {
		return new Builder();
	}

	/**
	 * Constructor for EcgMeasurementList.
	 * @param builder Builder
	 */
	private EcgMeasurementList(final Builder builder) {
		if (builder.hasEcgTimestamp ) {
			this.ecgTimestamp = builder.ecgTimestamp;
			this.measurementId = builder.measurementId;
			this.hasMeasurementId = builder.hasMeasurementId;
		} else {
			throw new UninitializedMessageException("Not all required fields were included (false = not included in message), " +
				" ecgTimestamp:" + builder.hasEcgTimestamp + "");
		}
	}

	/**
	 * The Class Builder.
	 */
	public static class Builder {

		/** The ecg timestamp. */
		private long ecgTimestamp;

		/** The has ecg timestamp. */
		private boolean hasEcgTimestamp = false;

		/** The measurement id. */
		private int measurementId;

		/** The has measurement id. */
		private boolean hasMeasurementId = false;


		/**
		 * Instantiates a new builder.
		 */
		private Builder() {
		}

		/**
		 * Method setEcgTimestamp.
		 * @param ecgTimestamp long
		 * @return Builder
		 */
		public Builder setEcgTimestamp(final long ecgTimestamp) {
			this.ecgTimestamp = ecgTimestamp;
			this.hasEcgTimestamp = true;
			return this;
		}

		/**
		 * Method setMeasurementId.
		 * @param measurementId int
		 * @return Builder
		 */
		public Builder setMeasurementId(final int measurementId) {
			this.measurementId = measurementId;
			this.hasMeasurementId = true;
			return this;
		}

		/**
		 * Method build.
		 * @return EcgMeasurementList
		 */
		public EcgMeasurementList build() {
			return new EcgMeasurementList(this);
		}
	}

	/**
	 * Method getEcgTimestamp.
	 * @return long
	 */
	public long getEcgTimestamp() {
		return ecgTimestamp;
	}

	/**
	 * Method getMeasurementId.
	 * @return int
	 */
	public int getMeasurementId() {
		return measurementId;
	}

	/**
	 * Method hasMeasurementId.
	 * @return boolean
	 */
	public boolean hasMeasurementId() {
		return hasMeasurementId;
	}

	/**
	 * Method toString.
	 * @return String
	 */
	public String toString() {
		final String TAB = "   ";
		String retValue = "";
		retValue += this.getClass().getName() + "(";
		retValue += "ecgTimestamp = " + this.ecgTimestamp + TAB;
		if(hasMeasurementId) retValue += "measurementId = " + this.measurementId + TAB;
		retValue += ")";

		return retValue;
	}

	// Override
	/**
	 * Method computeSize.
	 * @return int
	 * @see net.jarlehansen.protobuf.javame.CustomListWriter#computeSize()
	 */
	public int computeSize() {
		int totalSize = 0;
		totalSize += ComputeSizeUtil.computeLongSize(fieldNumberEcgTimestamp, ecgTimestamp);
		if(hasMeasurementId) totalSize += ComputeSizeUtil.computeIntSize(fieldNumberMeasurementId, measurementId);
		totalSize += computeNestedMessageSize();

		return totalSize;
	}

	/**
	 * Method computeNestedMessageSize.
	 * @return int
	 */
	private int computeNestedMessageSize() {
		int messageSize = 0;

		return messageSize;
	}

	// Override
	/**
	 * Method writeFields.
	 *
	 * @param writer OutputWriter
	 * @throws IOException Signals that an I/O exception has occurred.
	 * @see net.jarlehansen.protobuf.javame.CustomListWriter#writeFields(OutputWriter)
	 */
	public void writeFields(final OutputWriter writer) throws IOException {
		writer.writeLong(fieldNumberEcgTimestamp, ecgTimestamp);
		if(hasMeasurementId) writer.writeInt(fieldNumberMeasurementId, measurementId);
	}

	/**
	 * Method parseFields.
	 *
	 * @param reader InputReader
	 * @return EcgMeasurementList
	 * @throws IOException Signals that an I/O exception has occurred.
	 */
	static EcgMeasurementList parseFields(final InputReader reader) throws IOException {
		int nextFieldNumber = getNextFieldNumber(reader);
		final Builder builder = EcgMeasurementList.newBuilder();

		while (nextFieldNumber > 0) {
			if(!populateBuilderWithField(reader, builder, nextFieldNumber)) {
				reader.getPreviousTagDataTypeAndReadContent();
			}
			nextFieldNumber = getNextFieldNumber(reader);
		}

		return builder.build();
	}

	/**
	 * Method getNextFieldNumber.
	 *
	 * @param reader InputReader
	 * @return int
	 * @throws IOException Signals that an I/O exception has occurred.
	 */
	static int getNextFieldNumber(final InputReader reader) throws IOException {
		return reader.getNextFieldNumber();
	}

	/**
	 * Method populateBuilderWithField.
	 *
	 * @param reader InputReader
	 * @param builder Builder
	 * @param fieldNumber int
	 * @return boolean
	 * @throws IOException Signals that an I/O exception has occurred.
	 */
	static boolean populateBuilderWithField(final InputReader reader, final Builder builder, final int fieldNumber) throws IOException {
		boolean fieldFound = true;
		if (fieldNumber == fieldNumberEcgTimestamp) {
			builder.setEcgTimestamp(reader.readLong(fieldNumber));

		} else if (fieldNumber == fieldNumberMeasurementId) {
			builder.setMeasurementId(reader.readInt(fieldNumber));

		} else {
			fieldFound = false;
		}
		return fieldFound;
	}

	/**
	 * Method setUnknownTagHandler.
	 * @param unknownTagHandler UnknownTagHandler
	 */
	public static void setUnknownTagHandler(final UnknownTagHandler unknownTagHandler) {
		EcgMeasurementList.unknownTagHandler = unknownTagHandler;
	}

	/**
	 * Method parseFrom.
	 *
	 * @param data byte[]
	 * @return EcgMeasurementList
	 * @throws IOException Signals that an I/O exception has occurred.
	 */
	public static EcgMeasurementList parseFrom(final byte[] data) throws IOException {
		return parseFields(new InputReader(data, unknownTagHandler));
	}

	/**
	 * Method parseFrom.
	 *
	 * @param inputStream InputStream
	 * @return EcgMeasurementList
	 * @throws IOException Signals that an I/O exception has occurred.
	 */
	public static EcgMeasurementList parseFrom(final InputStream inputStream) throws IOException {
		return parseFields(new InputReader(inputStream, unknownTagHandler));
	}

	/**
	 * Method parseDelimitedFrom.
	 *
	 * @param inputStream InputStream
	 * @return EcgMeasurementList
	 * @throws IOException Signals that an I/O exception has occurred.
	 */
	public static EcgMeasurementList parseDelimitedFrom(final InputStream inputStream) throws IOException {
		final int limit = DelimitedSizeUtil.readDelimitedSize(inputStream);
		return parseFields(new InputReader(new DelimitedInputStream(inputStream, limit), unknownTagHandler));
	}
}